### ISSUE TITLE
Error: could not open uinput device

### ISSUE THREAD

**Issue by pbek** [ingbarrozo/espanso#1]
Thank you for your espanso package for Wayland!

I followed your steps from https://github.com/ingbarrozo/espanso/blob/main/README.md with setting up espanso, but when I register the service it crashes on every start-retry of the service definition (3sec) while taking the cursor focus. 😓 

When I try to launch `/nix/store/46ch7j5n9ypsig4mpg70npqbylyslbbq-espanso-2.2.1/bin/.espanso-wrapped launcher` directly I get:

```
15:52:10 [worker(6184)] [ERROR] Error: could not open uinput device
15:52:10 [worker(6184)] [ERROR] This might be due to a recent kernel update, please restart your PC so that the uinput module can be loaded correctly.
15:52:10 [worker(6184)] [ERROR] thread 'engine thread' panicked at 'failed to initialize injector module: could not open uinput device': espanso/src/cli/worker/engine/mod.rs:185
15:52:10 [worker(6184)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
15:52:10 [worker(6184)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
15:52:10 [daemon(6178)] [ERROR] received unexpected exit code from worker 101, exiting
thread 'main' panicked at espanso/src/cli/launcher/mod.rs:213:45:
failed to launch daemon: unexpected error, 'espanso daemon' returned a non-zero exit code.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

> Error: could not open uinput device

But I gave my user the `input` group...
Any advice?

**Comment by pbek** [comment]
Since `lsmod | grep uinput` gave me nothing, I tried loading it manually with `sudo modprobe uinput`. But still the same error...

**Comment by pbek** [comment]
Strange, `ls -l /dev/uinput` gave me: `crw------- 1 root root 10, 223  1. Mär 16:49 /dev/uinput`. After loading the upinput module manually, "fixing" the permissions and manually installing `wl-clipboard` I could launch espanso manually for a test... But that will not survive a reboot...

**Comment by pbek** [comment]
My very crude hack to make it work with plasma6 under Wayland:

https://github.com/pbek/nixcfg/commit/fd37b9e548c6f6cdc93b3db4bf348b89e449705b#diff-30e3d9bd8c832060653ed5849075f95e559011d73bad4d56c85251373d3bbc1d
